### ISSUE TITLE
Seems a good project... Wanted to know about the REST API

### ISSUE THREAD

**Issue by panbhatt** [chejen/keys-translations-manager#1]
HI Team,
  This project seems to be a good project to maintain all the translations for a big project. Just curious to know do we have an REST API in this so that we can get all the translations for a project at run time via some other language/framework. 
That would made it language agnostic and will help to make it more usable in the ecosystem.

**Comment by chejen** [comment]
It does have an REST API. I have updated the [README.md](https://github.com/chejen/keys-translations-manager/blob/master/README.md) for this, please let me know if it helps.

**Comment by chejen** [comment]
The usage of Rest API has been moved to [docs/rest-api.md](https://github.com/chejen/keys-translations-manager/blob/master/docs/rest-api.md)
