### ISSUE TITLE
startbootstrap-sb-admin  3.3.7+1  is not found.

### ISSUE THREAD

**Issue by kingbike** [chejen/keys-translations-manager#33]
the resource not found.
https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/3.3.7+1/js/sb-admin-2.min.js

**Comment by chejen** [comment]
@kingbike Thanks for reporting. I've made updates. Please pull the latest commit and give it a try. Let me know if it works, thanks!

**Comment by chunyu717** [comment]
It works , thanks .
